Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -32,7 +32,7 @@ jobs:
     - name: Build with Maven
       run: mvn -B package --file pom.xml
     - name: Generate Dependency Graph
-      run: cd service-a && mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph || echo "Dependency graph step failed, skipping..."
+      run: cd patient-service && mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph || echo "Dependency graph step failed, skipping..."
 
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
     - name: Update dependency graph
